package com.hoifu.form;

import org.eevolution.model.MPPProductBOM;
import org.eevolution.model.MPPProductBOMLine;
import org.adempiere.webui.editor.WSearchEditor;
import org.adempiere.webui.event.ValueChangeListener;
import org.compiere.model.MLookup;
import org.compiere.model.MLookupFactory;
import org.compiere.model.MColumn;
import org.compiere.model.MProduct;
import org.compiere.model.MUOM;
import org.compiere.model.PO;
import org.compiere.model.Query;
import org.compiere.util.Language;
import org.compiere.util.DisplayType;
import java.util.Properties;
import java.util.Random;

import org.adempiere.webui.util.TreeItemAction;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import org.adempiere.util.Callback;
import org.adempiere.webui.component.Borderlayout;
import org.adempiere.webui.component.Button;
import org.adempiere.webui.component.Checkbox;
import org.adempiere.webui.component.ConfirmPanel;
import org.adempiere.webui.component.Grid;
import org.adempiere.webui.component.GridFactory;
import org.adempiere.webui.component.Label;
import org.adempiere.webui.component.Panel;
import org.adempiere.webui.component.Row;
import org.adempiere.webui.component.Rows;
import org.adempiere.webui.component.SimpleTreeModel;
import org.adempiere.webui.component.Textbox;
import org.adempiere.webui.panel.ADForm;
import org.adempiere.webui.panel.CustomForm;
import org.adempiere.webui.panel.IFormController;
import org.adempiere.webui.session.SessionManager;
import org.adempiere.webui.util.TreeUtils;
import org.adempiere.webui.util.ZKUpdateUtil;
import org.adempiere.webui.window.Dialog;
import org.compiere.util.CLogger;
import org.compiere.util.Env;
import org.compiere.util.Msg;
import org.zkoss.zk.ui.event.Event;
import org.zkoss.zk.ui.event.EventListener;
import org.zkoss.zk.ui.event.Events;
import org.zkoss.zul.Center;
import org.zkoss.zul.DefaultTreeNode;
import org.zkoss.zul.Hlayout;
import org.zkoss.zul.North;
import org.zkoss.zul.Radio;
import org.zkoss.zul.Radiogroup;
import org.zkoss.zul.South;
import org.zkoss.zul.Space;
import org.zkoss.zul.Tree;
import org.zkoss.zul.TreeNode;
import org.zkoss.zul.Treecol;
import org.zkoss.zul.Treecols;
import org.zkoss.zul.Treeitem;
import org.zkoss.zul.Vlayout;
import org.zkoss.zul.West;
import org.zkoss.zul.Menuitem;
import org.zkoss.zul.Menupopup;
import org.zkoss.zul.Treerow;
import org.zkoss.zk.ui.event.DropEvent;

/**
 * 可编辑的BOM树表单 - 支持增删改节点
 */
@org.idempiere.ui.zk.annotation.Form(name = "com.hoifu.form.GenerateTreeBOM")
public class GenerateTreeBOM implements IFormController, EventListener<Event> {

	private static final CLogger log = CLogger.getCLogger(GenerateTreeBOM.class);

	// UI组件
	private CustomForm m_frame = new CustomForm();
	private Tree m_tree = new Tree();
	private Borderlayout mainLayout = new Borderlayout();
	private Panel northPanel = new Panel();
	private Panel southPanel = new Panel();
	private Label treeInfo = new Label();
	private West west = new West();
	private Panel treePane = new Panel();
	private ConfirmPanel confirmPanel = new ConfirmPanel(true);
	private Hlayout northLayout = new Hlayout();
	private Hlayout southLayout = new Hlayout();
	private Checkbox treeExpand = new Checkbox();
	// 在类的成员变量区域添加
	private Set<Integer> expandedNodeIds = new HashSet<>();
	// 右侧详情编辑面板
	private Panel detailPanel = new Panel();
	private Grid detailGrid = GridFactory.newGridLayout();

	// 第一行:物料类型选择
	private Radiogroup rgProductType = new Radiogroup();
	private Radio radioLinkExisting = new Radio();
	private Radio radioCreateNew = new Radio();

	// 第一行右侧:物料选择器(关联已有物料时显示)
	private WSearchEditor fieldProduct;

	// 第一行右侧:半成品名称(创建半成品时显示)
	private Label lblAutoGeneratedName = new Label();

	// 操作按钮
	private Button btnAddChild = new Button();
	private Button btnDelete = new Button();
	private Button btnSave = new Button();

	private Textbox txtName = new Textbox();
	private Textbox txtType = new Textbox();
	// 在类的成员变量区域添加
	private Textbox txtDescription = new Textbox();
	private Textbox txtUnit = new Textbox();
	private Textbox txtSortOrder = new Textbox();
	// 数据存储
	private SimpleTreeNode m_selectedNode;
	private Map<Integer, ProductData> productMap = new HashMap<>();

	// 变更跟踪
	private Map<Integer, ProductData> pendingChanges = new HashMap<>();
	private Set<Integer> pendingDeletes = new HashSet<>();
	private List<ProductData> pendingInserts = new ArrayList<>();
	private int nextTempId = -1; // 临时ID用于新增节点

	private int m_WindowNo = 0;
	private WSearchEditor fieldBOM; // BOM搜索字段
	private Label labelBOM = new Label();

	private ValueChangeListener productValueChangeListener;

	/**
	 * 产品数据类
	 */
	private static class ProductData implements Cloneable {
		// 核心标识
		int id; // 节点唯一ID(正数=真实物料ID, 负数=虚拟节点临时ID)
		String name; // 显示名称
		Integer parentId; // 父节点ID
		int sortOrder; // 排序序号
		String unit; // 计量单位

		// 虚拟节点专用字段
		boolean isVirtual; // true=虚拟节点(需要创建BOM关系), false=真实节点(已有BOM关系)
		boolean isLinkExisting; // true=选择已有物料, false=创建新物料(仅虚拟节点使用)
		Integer linkedProductId; // 选择的物料ID(仅当isLinkExisting=true时使用)

		// BOM相关
		String componentType; // 工序类型
		String description; // 描述(仅真实节点从数据库加载)

		// 缓存MPPProductBOM的自定义字段
		Map<String, Object> bomCustomFields = new HashMap<>();

		// 缓存M_Product的自定义字段
		Map<String, Object> productCustomFields = new HashMap<>();

		ProductData(int id, String name, String description, String unit, Integer parentId, int sortOrder) {
			this.id = id;
			this.name = name;
			this.description = description;
			this.unit = unit;
			this.parentId = parentId;
			this.sortOrder = sortOrder;
			this.isVirtual = false;
			this.isLinkExisting = false;
			this.linkedProductId = null;
			this.componentType = null;
		}

		@Override
		protected ProductData clone() {
			ProductData cloned = new ProductData(id, name, description, unit, parentId, sortOrder);
			cloned.isVirtual = this.isVirtual;
			cloned.componentType = this.componentType;
			cloned.isLinkExisting = this.isLinkExisting;
			cloned.linkedProductId = this.linkedProductId;
			// 复制自定义字段缓存
			cloned.bomCustomFields.putAll(this.bomCustomFields);
			cloned.productCustomFields.putAll(this.productCustomFields);
			return cloned;
		}
	}

	/**
	 * 树节点类
	 */
	class SimpleTreeNode extends DefaultTreeNode<Object> {
		private static final long serialVersionUID = 1L;
		private ProductData data;

		public SimpleTreeNode(ProductData data, List<TreeNode<Object>> children) {
			super(data, children);
			this.data = data;
		}

		public SimpleTreeNode(ProductData data) {
			super(data);
			this.data = data;
		}

		public ProductData getProductData() {
			return data;
		}

		@Override
		public String toString() {
			ProductData data = getProductData();

			if (!data.isVirtual) {
				// 真实节点: 物料编码_物料名称[单位]
				return data.name + " [" + data.unit + "]";
			} else {
				// 虚拟节点: 使用生成的名称
				return data.name;
			}
		}
	}

	/**
	 * 处理树节点拖拽事件
	 */
	private class BOMTreeOnDropListener implements EventListener<Event> {

		@Override
		public void onEvent(Event event) throws Exception {
			if (event instanceof DropEvent) {
				DropEvent de = (DropEvent) event;
				if (de.getDragged() != de.getTarget()) {
					Treeitem src = (Treeitem) ((Treerow) de.getDragged()).getParent();
					Treeitem target = (Treeitem) ((Treerow) de.getTarget()).getParent();

					SimpleTreeNode srcNode = (SimpleTreeNode) src.getValue();
					SimpleTreeNode targetNode = (SimpleTreeNode) target.getValue();

					moveNode(srcNode, targetNode);
				}
			}
		}

		/**
		 * 移动节点
		 */
		private void moveNode(SimpleTreeNode movingNode, SimpleTreeNode toNode) {
			if (movingNode == toNode) {
				return;
			}

			ProductData movingData = movingNode.getProductData();

			// 只有根节点不能移动
			if (movingData.parentId == null) {
				Dialog.warn(0, "不能移动根节点");
				return;
			}

			// 不能将节点移动到自己的子节点下
			if (isDescendant(toNode, movingNode)) {
				Dialog.warn(0, "不能将节点移动到自己的子节点下");
				return;
			}

			// 直接显示移动菜单,让用户选择
			showMoveMenu(movingNode, toNode);
		}

		/**
		 * 显示移动选项菜单
		 */
		private void showMoveMenu(SimpleTreeNode movingNode, SimpleTreeNode toNode) {
			Object rawModel = m_tree.getModel();
			if (!(rawModel instanceof SimpleTreeModel)) {
				log.severe("树模型类型不匹配");
				return;
			}
			SimpleTreeModel model = (SimpleTreeModel) rawModel;
			int[] path = model.getPath(toNode);
			Treeitem toItem = m_tree.renderItemByPath(path);

			Menupopup popup = new Menupopup();

			Menuitem insertAfter = new Menuitem("插入到后面");
			insertAfter.addEventListener(Events.ON_CLICK, e -> {
				moveNodeAfter(movingNode, toNode);
				popup.close();
			});
			popup.appendChild(insertAfter);

			Menuitem moveInto = new Menuitem("移入此节点");
			moveInto.addEventListener(Events.ON_CLICK, e -> {
				moveNodeInto(movingNode, toNode);
				popup.close();
			});
			popup.appendChild(moveInto);

			popup.setPage(m_tree.getPage());
			popup.open(toItem.getTreerow());
		}

		/**
		 * 将节点插入到目标节点后面
		 */
		private void moveNodeAfter(SimpleTreeNode movingNode, SimpleTreeNode toNode) {
			Object rawModel = m_tree.getModel();
			if (!(rawModel instanceof SimpleTreeModel)) {
				log.severe("树模型类型不匹配");
				return;
			}
			SimpleTreeModel model = (SimpleTreeModel) rawModel;
			ProductData movingData = movingNode.getProductData();
			ProductData toData = toNode.getProductData();

			// 检查目标节点是否是根节点
			if (toData.parentId == null) {
				Dialog.warn(0, "不能将节点移动到根节点后面");
				return;
			}

			SimpleTreeNode parent = (SimpleTreeNode) model.getParent(toNode);
			ProductData parentData = parent.getProductData();

			// 从原位置移除
			model.removeNode(movingNode);

			// 插入到目标节点后面
			int index = parent.getChildren().indexOf(toNode) + 1;
			model.addNode(parent, movingNode, index);

			// 更新数据(真实节点和虚拟节点都需要更新)
			movingData.parentId = parentData.id;
			movingData.sortOrder = index;

			// 更新同级节点的排序
			updateSiblingsSortOrder(parent);

			// 刷新树
			try {
				rebuildTreeFromMemory();
			} catch (Exception e) {
				log.log(Level.SEVERE, "刷新树失败", e);
			}

		}

		/**
		 * 将节点移入目标节点(作为第一个子节点)
		 */
		private void moveNodeInto(SimpleTreeNode movingNode, SimpleTreeNode toNode) {
			Object rawModel = m_tree.getModel();
			if (!(rawModel instanceof SimpleTreeModel)) {
				log.severe("树模型类型不匹配");
				return;
			}
			SimpleTreeModel model = (SimpleTreeModel) rawModel;

			ProductData movingData = movingNode.getProductData();
			ProductData toData = toNode.getProductData();

			// *** 检查目标节点是否是虚拟根节点 ***
			if (toData.id == 0) {
				Dialog.warn(0, "不能将节点移动到虚拟根节点下");
				return;
			}

			// 从原位置移除
			model.removeNode(movingNode);

			// 移入目标节点
			model.addNode(toNode, movingNode, 0);

			// 更新数据
			movingData.parentId = toData.id;
			movingData.sortOrder = 0;

			// 更新同级节点的排序
			updateSiblingsSortOrder(toNode);

			// 刷新树
			try {
				rebuildTreeFromMemory();
			} catch (Exception e) {
				log.log(Level.SEVERE, "刷新树失败", e);
			}

		}

		/**
		 * 检查 node 是否是 ancestor 的后代
		 */
		private boolean isDescendant(SimpleTreeNode node, SimpleTreeNode ancestor) {
			// 使用 Object 作为中间类型来避免泛型转换问题
			Object rawModel = m_tree.getModel();
			if (!(rawModel instanceof SimpleTreeModel)) {
				log.severe("树模型类型不匹配");
				return false;
			}
			SimpleTreeModel model = (SimpleTreeModel) rawModel;

			SimpleTreeNode parent = (SimpleTreeNode) model.getParent(node);

			while (parent != null) {
				if (parent == ancestor) {
					return true;
				}
				parent = (SimpleTreeNode) model.getParent(parent);
			}

			return false;
		}

		/**
		 * 更新同级节点的排序
		 */
		private void updateSiblingsSortOrder(SimpleTreeNode parent) {
			ProductData parentData = parent.getProductData();

			for (int i = 0; i < parent.getChildCount(); i++) {
				SimpleTreeNode child = (SimpleTreeNode) parent.getChildAt(i);
				ProductData childData = child.getProductData();

				if (childData.sortOrder != i) {
					childData.sortOrder = i;
				}
			}
		}
	}

	/**
	 * 构造函数
	 */
	public GenerateTreeBOM() {
		try {
			preInit(); // 先初始化BOM搜索字段
			layoutForm();
			// 不自动加载,等待用户选择BOM
		} catch (Exception e) {
			log.log(Level.SEVERE, "GenerateTreeBOM.init", e);
		}
	}

	/**
	 * 从内存中的productMap重建树(不重新加载数据库)
	 */
	private void rebuildTreeFromMemory() throws Exception {
		// 保存当前展开的节点ID
		if (m_tree.getTreechildren() != null) {
			saveExpandedState(m_tree);
		}

		// 查找所有根产品
		List<ProductData> rootProducts = new ArrayList<>();
		for (ProductData pd : productMap.values()) {
			if (pd.parentId == null) {
				rootProducts.add(pd);
			}
		}

		if (rootProducts.isEmpty()) {
			log.warning("未找到根产品");
			return;
		}

		rootProducts.sort((a, b) -> Integer.compare(a.sortOrder, b.sortOrder));

		SimpleTreeNode dummyRoot = new SimpleTreeNode(new ProductData(0, "Root", "", "", null, 0),
				new ArrayList<TreeNode<Object>>());

		for (ProductData rootProduct : rootProducts) {
			SimpleTreeNode rootNode = new SimpleTreeNode(rootProduct, new ArrayList<TreeNode<Object>>());
			dummyRoot.add(rootNode);
			buildTree(rootNode, rootProduct.id);
		}

		try {
			m_tree.setModel(null);
		} catch (Exception e) {
		}

		if (m_tree.getTreecols() != null)
			m_tree.getTreecols().detach();
		if (m_tree.getTreefoot() != null)
			m_tree.getTreefoot().detach();
		if (m_tree.getTreechildren() != null)
			m_tree.getTreechildren().detach();

		Treecols treeCols = new Treecols();
		m_tree.appendChild(treeCols);
		Treecol treeCol = new Treecol();
		treeCols.appendChild(treeCol);

		SimpleTreeModel model = new SimpleTreeModel(dummyRoot);
		model.setItemDraggable(true);
		model.addOnDropEventListener(new BOMTreeOnDropListener());

		// 恢复展开状态
		if (!expandedNodeIds.isEmpty()) {
			addOpenPathsToModel(model, dummyRoot);
		}

		m_tree.setPageSize(1);
		m_tree.setItemRenderer(model);
		m_tree.setModel(model);
	}

	private void preInit() throws Exception {
		m_WindowNo = m_frame.getWindowNo();
		Properties ctx = Env.getCtx();
		Language language = Language.getLoginLanguage();

		// 创建PP_Product_BOM搜索字段
		MLookup m_fieldBOM = MLookupFactory.get(ctx, m_WindowNo,
				MColumn.getColumn_ID("PP_Product_BOM", "PP_Product_BOM_ID"), DisplayType.Search, language,
				"PP_Product_BOM_ID", 0, false, " PP_Product_BOM.IsActive = 'Y'");

		fieldBOM = new WSearchEditor("PP_Product_BOM_ID", true, false, true, m_fieldBOM) {
			public void setValue(Object value) {
				super.setValue(value);
				confirmPanel.getButton(ConfirmPanel.A_REFRESH).setFocus(true);
			}
		};

		// 创建M_Product搜索字段的Lookup
		MLookup productLookup = MLookupFactory.get(ctx, m_WindowNo,
				MColumn.getColumn_ID(MProduct.Table_Name, "M_Product_ID"), DisplayType.Search, language,
				MProduct.COLUMNNAME_M_Product_ID, 0, false, " M_Product.IsActive = 'Y'");

		fieldProduct = new WSearchEditor("M_Product_ID", true, false, true, productLookup);

		// 创建并保存监听器引用
		productValueChangeListener = e -> {
			System.out.println("=== ValueChangeListener 触发 ===");
			System.out.println("旧值: " + e.getOldValue() + ", 新值: " + e.getNewValue());

			// 直接使用事件中的新值,而不是调用 getValue()
			if (e.getNewValue() != null && e.getNewValue() instanceof Integer) {
				Integer productId = (Integer) e.getNewValue();
				onProductSelectedWithId(productId);
			}
		};

		fieldProduct.addValueChangeListener(productValueChangeListener);
		System.out.println("物料选择器监听器已添加");
	}

	// 新增方法,直接接收 productId
	private void onProductSelectedWithId(Integer productId) {
		System.out.println("=== onProductSelectedWithId 被调用 ===");
		System.out.println("选择的物料ID: " + productId);

		if (productId == null || productId == 0 || m_selectedNode == null) {
			System.out.println("退出: productId=" + productId);
			return;
		}

		ProductData pd = m_selectedNode.getProductData();
		System.out.println("当前节点ID: " + pd.id + ", 原linkedProductId: " + pd.linkedProductId);

		pd.linkedProductId = productId;
		pd.isLinkExisting = true;
		System.out.println("更新后linkedProductId: " + pd.linkedProductId);

		MProduct product = MProduct.get(Env.getCtx(), productId);
		if (product != null) {
			String rootValue = getRootProductValue();
			int level = calculateNodeLevel(pd);
			int sequence = calculateSequenceInLevel(pd);
			String serialCode = String.format("%04d", Math.abs(pd.id));

			pd.name = String.format("%s_%d_%d_%s_%s", rootValue, level, sequence, product.getValue(), serialCode);
			System.out.println("生成的新名称: " + pd.name);

			int selectedNodeId = pd.id;

			try {
				System.out.println("开始刷新树...");
				rebuildTreeFromMemory();
				System.out.println("树刷新完成");
			} catch (Exception e) {
				log.log(Level.SEVERE, "刷新树失败", e);
			}
		}
	}

	/**
	 * 从数据库加载BOM数据并转换为parent_id层级结构
	 */
	private void loadBOMFromDatabase() {
		Integer bomId = (Integer) fieldBOM.getValue();
		if (bomId == null || bomId == 0) {
			Dialog.warn(0, "请先选择一个BOM");
			return;
		}

		productMap.clear();
		pendingChanges.clear();
		pendingDeletes.clear();
		pendingInserts.clear();

		try {
			PO.setCrossTenantSafe();

			MPPProductBOM bom = new MPPProductBOM(Env.getCtx(), bomId, null);
			String rootBOMRevision = bom.getRevision(); // 可能为null

			MProduct rootProduct = MProduct.get(Env.getCtx(), bom.getM_Product_ID());
			MUOM rootUOM = MUOM.get(Env.getCtx(), rootProduct.getC_UOM_ID());

			// 创建根节点
			ProductData rootData = new ProductData(rootProduct.getM_Product_ID(),
					rootProduct.getValue() + "_" + rootProduct.getName(),
					rootProduct.getDescription() != null ? rootProduct.getDescription() : "", rootUOM.getUOMSymbol(),
					null, 0);
			rootData.isVirtual = false;
			rootData.linkedProductId = rootProduct.getM_Product_ID();

			// 保存根节点BOM的自定义字段
			rootData.bomCustomFields.put("nRate", bom.get_Value("nRate"));
			// 保存根节点Product的自定义字段
			rootData.productCustomFields.put("M_Product_Category_ID_L1",
					rootProduct.get_Value("M_Product_Category_ID_L1"));
			rootData.productCustomFields.put("M_Product_Category_ID_L2",
					rootProduct.get_Value("M_Product_Category_ID_L2"));

			productMap.put(rootData.id, rootData);

			// 如果Revision为空,直接通过BOM_ID加载第一层子节点
			if (rootBOMRevision == null || rootBOMRevision.trim().isEmpty()) {
				loadFirstLevelByBOMId(bomId, rootData.id, rootBOMRevision);
			} else {
				// 有版本号,使用递归加载
				loadBOMNodeWithGrouping(rootProduct.getM_Product_ID(), rootData.id, 0, rootBOMRevision);
			}

			treeInfo.setText("BOM: " + bom.getValue() + " - " + rootProduct.getValue());

		} catch (Exception e) {
			log.log(Level.SEVERE, "加载BOM失败", e);
			Dialog.error(0, "加载BOM失败: " + e.getMessage());
		} finally {
			PO.clearCrossTenantSafe();
		}
	}

	/**
	 * 当根节点Revision为空时,直接通过BOM_ID加载第一层子节点
	 */
	private void loadFirstLevelByBOMId(int bomId, int parentNodeId, String revision) {
		try {
			PO.setCrossTenantSafe();

			// 直接通过BOM_ID查询第一层子节点
			String whereClause = "PP_Product_BOM_ID=? AND IsActive='Y'";
			List<MPPProductBOMLine> bomLinesList = new Query(Env.getCtx(), MPPProductBOMLine.Table_Name, whereClause,
					null).setParameters(bomId).setOrderBy("Line").list();

			if (bomLinesList.isEmpty()) {
				return;
			}

			// 按ComponentType分组
			Map<String, List<MPPProductBOMLine>> groupedLines = new HashMap<>();
			for (MPPProductBOMLine line : bomLinesList) {
				String componentType = line.getComponentType();
				if (componentType == null || componentType.isEmpty()) {
					componentType = "DEFAULT";
				}
				groupedLines.computeIfAbsent(componentType, k -> new ArrayList<>()).add(line);
			}

			int groupSortOrder = 0;

			// 为每个ComponentType创建虚拟分组节点或直接添加物料
			for (Map.Entry<String, List<MPPProductBOMLine>> entry : groupedLines.entrySet()) {
				String componentType = entry.getKey();
				List<MPPProductBOMLine> lines = entry.getValue();

				if (lines.size() == 1) {
					// 单条数据,直接挂在父节点下
					MPPProductBOMLine line = lines.get(0);
					int childNodeId = addBOMLineAsProduct(line, parentNodeId, groupSortOrder++);

					// 递归处理该子节点的子节点(如果有版本号)
					if (childNodeId > 0 && revision != null && !revision.trim().isEmpty()) {
						loadBOMNodeWithGrouping(line.getM_Product_ID(), childNodeId, 0, revision);
					}
				} else {
					// 多条数据,创建虚拟分组节点
					int virtualNodeId = -(componentType.hashCode() & 0x7FFFFFFF);

					ProductData virtualNode = new ProductData(virtualNodeId, "", "", "组", parentNodeId,
							groupSortOrder++);
					virtualNode.isVirtual = true;
					virtualNode.isLinkExisting = false;
					virtualNode.componentType = componentType;
					virtualNode.name = generateSemiProductName(virtualNode);
					productMap.put(virtualNodeId, virtualNode);

					// 将该组的所有物料添加为虚拟节点的子节点
					int lineSortOrder = 0;
					for (MPPProductBOMLine line : lines) {
						int childNodeId = addBOMLineAsProduct(line, virtualNodeId, lineSortOrder++);

						// 递归处理该子节点的子节点(如果有版本号)
						if (childNodeId > 0 && revision != null && !revision.trim().isEmpty()) {
							loadBOMNodeWithGrouping(line.getM_Product_ID(), childNodeId, 0, revision);
						}
					}
				}
			}

		} catch (Exception e) {
			log.log(Level.SEVERE, "加载第一层BOM节点失败", e);
		} finally {
			PO.clearCrossTenantSafe();
		}
	}

	/**
	 * 递归加载BOM节点并按ComponentType分组
	 * 
	 * @param parentProductId 父节点的物料ID
	 * @param parentNodeId    父节点在productMap中的ID
	 * @param baseSortOrder   基础排序号
	 */
	private void loadBOMNodeWithGrouping(int parentProductId, int parentNodeId, int baseSortOrder, String revision) {
		try {
			PO.setCrossTenantSafe();

			MProduct parentProduct = MProduct.get(Env.getCtx(), parentProductId);

			// 根据物料ID和版本号查询BOM,取最近创建的
			String whereClause = "M_Product_ID=? AND Revision=? AND IsActive='Y'";
			List<MPPProductBOM> boms = new Query(Env.getCtx(), MPPProductBOM.Table_Name, whereClause, null)
					.setParameters(parentProductId, revision).setOrderBy("Created DESC") // 按创建时间降序,取最新的
					.list();

			if (boms == null || boms.isEmpty()) {
				return; // 没有找到对应版本的BOM,说明是叶子节点
			}

			MPPProductBOM parentBOM = boms.get(0); // 取最近创建的

			// 查询该BOM的所有行
			String bomLineWhere = "PP_Product_BOM_ID=? AND IsActive='Y'";
			List<MPPProductBOMLine> bomLinesList = new Query(Env.getCtx(), MPPProductBOMLine.Table_Name, bomLineWhere,
					null).setParameters(parentBOM.getPP_Product_BOM_ID()).setOrderBy("Line").list();

			if (bomLinesList == null || bomLinesList.isEmpty()) {
				return;
			}

			MPPProductBOMLine[] bomLines = bomLinesList.toArray(new MPPProductBOMLine[0]);

			// 按ComponentType分组
			Map<String, List<MPPProductBOMLine>> groupedLines = new HashMap<>();
			for (MPPProductBOMLine line : bomLines) {
				String componentType = line.getComponentType();
				if (componentType == null || componentType.isEmpty()) {
					componentType = "DEFAULT";
				}
				groupedLines.computeIfAbsent(componentType, k -> new ArrayList<>()).add(line);
			}

			int groupSortOrder = baseSortOrder;

			for (Map.Entry<String, List<MPPProductBOMLine>> entry : groupedLines.entrySet()) {
				String componentType = entry.getKey();
				List<MPPProductBOMLine> lines = entry.getValue();

				if (lines.size() == 1) {
					// 单条数据,直接挂在父节点下
					MPPProductBOMLine line = lines.get(0);
					int childNodeId = addBOMLineAsProduct(line, parentNodeId, groupSortOrder++);

					// 递归处理该子节点的子节点,传递相同的版本号
					if (childNodeId > 0) {
						loadBOMNodeWithGrouping(line.getM_Product_ID(), childNodeId, 0, revision);
					}
				} else {
					// 多条数据,创建虚拟分组节点
					int virtualNodeId = -(componentType.hashCode() & 0x7FFFFFFF);

					ProductData virtualNode = new ProductData(virtualNodeId, "", "", "组", parentNodeId,
							groupSortOrder++);
					virtualNode.isVirtual = true;
					virtualNode.isLinkExisting = false;
					virtualNode.componentType = componentType;
					virtualNode.name = generateSemiProductName(virtualNode);
					productMap.put(virtualNodeId, virtualNode);

					int lineSortOrder = 0;
					for (MPPProductBOMLine line : lines) {
						int childNodeId = addBOMLineAsProduct(line, virtualNodeId, lineSortOrder++);

						// 递归处理该子节点的子节点,传递相同的版本号
						if (childNodeId > 0) {
							loadBOMNodeWithGrouping(line.getM_Product_ID(), childNodeId, 0, revision);
						}
					}
				}
			}

		} catch (Exception e) {
			log.log(Level.SEVERE, "加载BOM节点失败", e);
		} finally {
			PO.clearCrossTenantSafe();
		}
	}

	/**
	 * 添加BOM行作为产品节点
	 * 
	 * @return 创建的节点ID,如果失败返回-1
	 */
	private int addBOMLineAsProduct(MPPProductBOMLine line, int parentId, int sortOrder) {
		MProduct product = MProduct.get(Env.getCtx(), line.getM_Product_ID());
		if (product == null) {
			return -1;
		}

		MUOM uom = MUOM.get(Env.getCtx(), product.getC_UOM_ID());
		ProductData pd = new ProductData(product.getM_Product_ID(), product.getValue() + "_" + product.getName(),
				product.getDescription() != null ? product.getDescription() : "", uom.getUOMSymbol(), parentId,
				sortOrder);
		pd.isVirtual = false;
		pd.linkedProductId = product.getM_Product_ID();
		pd.componentType = line.getComponentType();

		// 缓存Product的自定义字段
		pd.productCustomFields.put("M_Product_Category_ID_L1", product.get_Value("M_Product_Category_ID_L1"));
		pd.productCustomFields.put("M_Product_Category_ID_L2", product.get_Value("M_Product_Category_ID_L2"));

		// 获取该BOM行对应的BOM头，缓存BOM的自定义字段
		MPPProductBOM bom = new MPPProductBOM(Env.getCtx(), line.getPP_Product_BOM_ID(), null);
		pd.bomCustomFields.put("nRate", bom.get_Value("nRate"));

		productMap.put(pd.id, pd);
		return pd.id;
	}

	/**
	 * 布局表单 - 参考WTreeBOM和WTreeMaintenance的布局
	 */
	private void layoutForm() {
		ZKUpdateUtil.setWidth(m_frame, "99%");
		ZKUpdateUtil.setHeight(m_frame, "100%");
		m_frame.setStyle("position: absolute; padding: 0; margin: 0");
		m_frame.appendChild(mainLayout);
		ZKUpdateUtil.setHflex(mainLayout, "1");
		ZKUpdateUtil.setHeight(mainLayout, "100%");

		// 北部面板
		northPanel.appendChild(northLayout);

		// 添加BOM搜索标签和字段
		labelBOM.setText("BOM:");
		northLayout.setValign("middle");
		northLayout.setStyle("padding: 4px;");
		northLayout.appendChild(labelBOM.rightAlign());
		ZKUpdateUtil.setWidth(fieldBOM.getComponent(), "300px");
		northLayout.appendChild(fieldBOM.getComponent());
		northLayout.appendChild(new Space());

		treeInfo.setText("BOM树形结构 - 可编辑模式");
		northLayout.appendChild(treeInfo);

		btnAddChild.setLabel("添加子节点");
		btnAddChild.addEventListener(Events.ON_CLICK, this);
		northLayout.appendChild(btnAddChild);

		btnDelete.setLabel("删除节点");
		btnDelete.addEventListener(Events.ON_CLICK, this);
		northLayout.appendChild(btnDelete);

		North north = new North();
		north.appendChild(northPanel);
		ZKUpdateUtil.setVflex(north, "min");
		ZKUpdateUtil.setWidth(northPanel, "100%");
		mainLayout.appendChild(north);

		// 南部面板 - 操作按钮
		southPanel.appendChild(southLayout);
		ZKUpdateUtil.setVflex(southPanel, "min");
		treeExpand.setText("展开树");
		treeExpand.addActionListener(this);

		South south = new South();
		south.appendChild(southPanel);
		ZKUpdateUtil.setVflex(south, "min");
		ZKUpdateUtil.setWidth(southPanel, "100%");
		mainLayout.appendChild(south);

		southLayout.setValign("middle");
		southLayout.setStyle("padding: 4px");
		ZKUpdateUtil.setHflex(southLayout, "1");
		ZKUpdateUtil.setVflex(southLayout, "min");
		southLayout.appendChild(treeExpand);
		ZKUpdateUtil.setHflex(treeExpand, "1");
		treeExpand.setStyle("float: left;");
		southLayout.appendChild(confirmPanel);
		ZKUpdateUtil.setHflex(confirmPanel, "1");
		confirmPanel.setStyle("float: right;");

		// 添加保存按钮到ConfirmPanel
		confirmPanel.addComponentsBeforeRight(confirmPanel.createButton(ConfirmPanel.A_REFRESH));
		btnSave.setLabel(Msg.getMsg(Env.getCtx(), "Save"));
		btnSave.addEventListener(Events.ON_CLICK, this);
		confirmPanel.addComponentsBeforeRight(btnSave);
		confirmPanel.addActionListener(this);

		// 西部面板 - 树形视图 (参考WTreeBOM的布局)
		mainLayout.appendChild(west);
		west.setSplittable(true);
		west.appendChild(treePane);
		treePane.appendChild(m_tree);
		m_tree.setStyle("border: none;");
		ZKUpdateUtil.setWidth(west, "40%"); // 左侧占40%
		west.setAutoscroll(true);
		m_tree.addEventListener(Events.ON_SELECT, this);

		// 中部面板 - 详情编辑区域 (参考WTreeMaintenance的East区域)
		Center center = new Center();
		mainLayout.appendChild(center);

		Vlayout centerLayout = new Vlayout();
		centerLayout.setStyle("padding: 10px;");
		ZKUpdateUtil.setHflex(centerLayout, "1"); // 添加这行
		ZKUpdateUtil.setVflex(centerLayout, "1"); // 添加这行
		center.appendChild(centerLayout);

		Label detailTitle = new Label("节点详情");
		detailTitle.setStyle("font-size: 16px; font-weight: bold; margin-bottom: 10px;");
		centerLayout.appendChild(detailTitle);

		detailPanel.setStyle("border: 1px solid #C0C0C0; padding: 10px; background: #FFFFFF;");
		centerLayout.appendChild(detailPanel);
		detailPanel.appendChild(detailGrid);
		ZKUpdateUtil.setHflex(detailPanel, "1");
		ZKUpdateUtil.setVflex(detailPanel, "1");

		// 添加这些行来确保Grid正确显示
		ZKUpdateUtil.setHflex(detailGrid, "1");
		ZKUpdateUtil.setVflex(detailGrid, "min");

		// 构建详情表单
		buildDetailForm();

		center.setAutoscroll(true);
	}

	/**
	 * 构建详情编辑表单
	 */
	private void buildDetailForm() {
		Rows rows = detailGrid.newRows();

		// === 第一行:物料类型选择 + 物料信息 ===
		Row rowFirstLine = rows.newRow();

		// 左侧:单选按钮
		Hlayout leftLayout = new Hlayout();
		leftLayout.setSpacing("10px");
		leftLayout.setValign("middle");

		// 先添加Radiogroup到布局
		leftLayout.appendChild(rgProductType);

		radioLinkExisting.setLabel("关联已有物料");
		radioLinkExisting.setRadiogroup(rgProductType);
		radioLinkExisting.addEventListener(Events.ON_CHECK, this);
		rgProductType.appendChild(radioLinkExisting); // 添加到group

		radioCreateNew.setLabel("创建半成品");
		radioCreateNew.setRadiogroup(rgProductType);
		radioCreateNew.setChecked(true); // 默认选中
		radioCreateNew.addEventListener(Events.ON_CHECK, this);
		rgProductType.appendChild(radioCreateNew); // 添加到group

		rowFirstLine.appendChild(leftLayout);

		// 右侧:动态显示区域(物料选择器 或 自动生成名称)
		Hlayout rightLayout = new Hlayout();
		rightLayout.setSpacing("10px");
		rightLayout.setValign("middle");
		ZKUpdateUtil.setHflex(rightLayout, "1");

		// 物料选择器(初始隐藏)
		try {
			Properties ctx = Env.getCtx();
			Language language = Language.getLoginLanguage();
			MLookup productLookup = MLookupFactory.get(ctx, m_WindowNo,
					MColumn.getColumn_ID(MProduct.Table_Name, "M_Product_ID"), DisplayType.Search, language,
					MProduct.COLUMNNAME_M_Product_ID, 0, false, " M_Product.IsActive = 'Y'");
			fieldProduct = new WSearchEditor("M_Product_ID", true, false, true, productLookup);
			fieldProduct.addValueChangeListener(e -> onProductSelected());
			ZKUpdateUtil.setWidth(fieldProduct.getComponent(), "100%");
			fieldProduct.getComponent().setVisible(false); // 初始隐藏
			rightLayout.appendChild(fieldProduct.getComponent());
		} catch (Exception e) {
			log.log(Level.SEVERE, "创建物料搜索器失败", e);
		}

		// 自动生成名称标签(初始显示)
		lblAutoGeneratedName.setStyle("font-weight: bold; color: #0066cc;");
		lblAutoGeneratedName.setValue("(请先选择节点)");
		rightLayout.appendChild(lblAutoGeneratedName);

		rowFirstLine.appendChild(rightLayout);

		setDetailFormEnabled(false);
		detailGrid.invalidate();
	}

	private void onProductTypeChange() {
		if (radioLinkExisting.isChecked()) {
			// 临时移除监听器,避免触发 onProductSelected
			fieldProduct.removeValuechangeListener(productValueChangeListener);

			fieldProduct.getComponent().setVisible(true);
			lblAutoGeneratedName.setVisible(false);

			// 清空物料选择器
			fieldProduct.setValue(null);

			// 重新添加监听器
			fieldProduct.addValueChangeListener(productValueChangeListener);

			if (m_selectedNode != null) {
				ProductData pd = m_selectedNode.getProductData();
				pd.isLinkExisting = true;
				pd.linkedProductId = null;
			}

		} else if (radioCreateNew.isChecked()) {
			fieldProduct.getComponent().setVisible(false);
			lblAutoGeneratedName.setVisible(true);

			if (m_selectedNode != null) {
				ProductData pd = m_selectedNode.getProductData();
				pd.isLinkExisting = false;
				// 直接使用 name 字段,不再使用 autoGeneratedName
				pd.name = generateSemiProductName(pd);
				lblAutoGeneratedName.setValue(pd.name);

				try {
					rebuildTreeFromMemory();
				} catch (Exception e) {
					log.log(Level.SEVERE, "刷新树失败", e);
				}
			}
		}
	}

	/**
	 * 生成半成品名称: 根节点物料编码_层数_序号_流水码
	 */
	private String generateSemiProductName(ProductData pd) {
		String rootValue = getRootProductValue();
		int level = calculateNodeLevel(pd);
		String serialCode = String.format("%04d", System.currentTimeMillis() % 10000);

		if (pd.isLinkExisting && pd.linkedProductId != null && pd.linkedProductId > 0) {
			// 已选择物料: 物料编码_层数_V_1_流水号_物料名称
			MProduct product = MProduct.get(Env.getCtx(), pd.linkedProductId);
			if (product != null) {
				return product.getValue() + "_" + level + "_V_1_" + serialCode + "_" + product.getName();
			}
		}

		// 创建新物料: 根节点物料编码_层数_V_1_流水号
		return rootValue + "_" + level + "_V_1_" + serialCode;
	}

	/**
	 * 获取根节点的物料编码
	 */
	private String getRootProductValue() {
		for (ProductData pd : productMap.values()) {
			if (pd.parentId == null) {
				// 从name中提取物料编码(格式: "编码_名称")
				String[] parts = pd.name.split("_");
				return parts.length > 0 ? parts[0] : "ROOT";
			}
		}
		return "ROOT";
	}

	/**
	 * 计算节点所在层数(根节点为0层)
	 */
	private int calculateNodeLevel(ProductData pd) {
		int level = 0;
		Integer currentParentId = pd.parentId;

		while (currentParentId != null) {
			level++;
			ProductData parent = productMap.get(currentParentId);
			if (parent == null)
				break;
			currentParentId = parent.parentId;
		}

		return level;
	}

	/**
	 * 计算节点在该层的序号
	 */
	private int calculateSequenceInLevel(ProductData pd) {
		int level = calculateNodeLevel(pd);

		// 找出同层的所有节点
		List<ProductData> sameLevelNodes = new ArrayList<>();
		for (ProductData other : productMap.values()) {
			if (calculateNodeLevel(other) == level) {
				sameLevelNodes.add(other);
			}
		}

		// 按sortOrder排序
		sameLevelNodes.sort((a, b) -> Integer.compare(a.sortOrder, b.sortOrder));

		// 找到当前节点的位置
		for (int i = 0; i < sameLevelNodes.size(); i++) {
			if (sameLevelNodes.get(i).id == pd.id) {
				return i + 1; // 序号从1开始
			}
		}

		return 1;
	}

	/**
	 * 启用/禁用详情表单
	 */
	private void setDetailFormEnabled(boolean enabled) {
		txtName.setDisabled(!enabled);
		txtType.setDisabled(!enabled);
		txtDescription.setDisabled(!enabled); // 添加这行
		txtUnit.setDisabled(!enabled); // 添加这行
		txtSortOrder.setDisabled(!enabled);
	}

	/**
	 * 加载BOM树
	 */
	private void action_loadBOM() throws Exception {
		// *** 先保存展开状态(在清空之前!) ***
		if (m_tree.getTreechildren() != null) {
			saveExpandedState(m_tree);
		}

		// *** 检查是否有未保存的修改 ***
		if (!pendingChanges.isEmpty() || !pendingDeletes.isEmpty() || !pendingInserts.isEmpty()) {
			Dialog.ask(0, "警告", "有未保存的修改,刷新将丢失这些修改。是否继续?", new Callback<Boolean>() {
				@Override
				public void onCallback(Boolean result) {
					if (result) {
						try {
							doLoadBOM();
						} catch (Exception e) {
							log.log(Level.SEVERE, "加载BOM失败", e);
						}
					}
				}
			});
			return;
		}

		doLoadBOM();
	}

	// *** 实际执行加载逻辑 ***
	private void doLoadBOM() throws Exception {
		// 如果fieldBOM有值,从数据库加载
		if (fieldBOM != null && fieldBOM.getValue() != null) {
			loadBOMFromDatabase();
		}

		// 查找所有根产品
		List<ProductData> rootProducts = new ArrayList<>();
		for (ProductData pd : productMap.values()) {
			if (pd.parentId == null) {
				rootProducts.add(pd);
			}
		}

		if (rootProducts.isEmpty()) {
			log.warning("未找到根产品");
			return;
		}

		// 后续构建树的逻辑保持不变 ...
		rootProducts.sort((a, b) -> Integer.compare(a.sortOrder, b.sortOrder));
		treeInfo.setText("BOM树形结构 - " + rootProducts.size() + " 个产品");

		SimpleTreeNode dummyRoot = new SimpleTreeNode(new ProductData(0, "Root", "", "", null, 0),
				new ArrayList<TreeNode<Object>>());

		for (ProductData rootProduct : rootProducts) {
			SimpleTreeNode rootNode = new SimpleTreeNode(rootProduct, new ArrayList<TreeNode<Object>>());
			dummyRoot.add(rootNode);
			buildTree(rootNode, rootProduct.id);
		}

		try {
			m_tree.setModel(null);
		} catch (Exception e) {
		}

		if (m_tree.getTreecols() != null)
			m_tree.getTreecols().detach();
		if (m_tree.getTreefoot() != null)
			m_tree.getTreefoot().detach();
		if (m_tree.getTreechildren() != null)
			m_tree.getTreechildren().detach();

		Treecols treeCols = new Treecols();
		m_tree.appendChild(treeCols);
		Treecol treeCol = new Treecol();
		treeCols.appendChild(treeCol);

		SimpleTreeModel model = new SimpleTreeModel(dummyRoot);

		// 启用拖拽功能
		model.setItemDraggable(true);

		// 添加拖拽监听器
		model.addOnDropEventListener(new BOMTreeOnDropListener());

		// 在设置模型前预先添加展开路径
		if (!expandedNodeIds.isEmpty()) {
			addOpenPathsToModel(model, dummyRoot);
		}

		m_tree.setPageSize(-1);
		m_tree.setItemRenderer(model);
		m_tree.setModel(model);

		if (expandedNodeIds.isEmpty()) {
			treeExpand.setChecked(false);
		}
	}

	/**
	 * 递归添加展开路径到模型
	 */
	private void addOpenPathsToModel(SimpleTreeModel model, SimpleTreeNode node) {
		if (node.getData() instanceof ProductData) {
			ProductData data = (ProductData) node.getData();
			if (expandedNodeIds.contains(data.id)) {
				int[] path = model.getPath(node);
				model.addOpenPath(path);
			}
		}

		// 递归处理子节点
		for (int i = 0; i < node.getChildCount(); i++) {
			SimpleTreeNode child = (SimpleTreeNode) node.getChildAt(i);
			addOpenPathsToModel(model, child);
		}
	}

	/**
	 * 保存当前树的展开状态
	 */
	private void saveExpandedState(Tree tree) {
		expandedNodeIds.clear();

		if (tree.getTreechildren() == null) {
			return;
		}

		TreeUtils.traverse(tree, new TreeItemAction() {
			@Override
			public void run(Treeitem treeItem) {
				if (treeItem.getValue() instanceof SimpleTreeNode) {
					SimpleTreeNode node = (SimpleTreeNode) treeItem.getValue();
					if (treeItem.isOpen()) {
						expandedNodeIds.add(node.getProductData().id);
					}
				}
			}
		});
	}

	/**
	 * 递归构建树结构
	 */
	private void buildTree(SimpleTreeNode parentNode, int parentId) {
		List<ProductData> children = new ArrayList<>();
		for (ProductData pd : productMap.values()) {
			if (pd.parentId != null && pd.parentId == parentId) {
				children.add(pd);
			}
		}

		children.sort((a, b) -> Integer.compare(a.sortOrder, b.sortOrder));

		for (ProductData child : children) {
			boolean isLeaf = !hasChildren(child.id);
			SimpleTreeNode childNode = isLeaf ? new SimpleTreeNode(child)
					: new SimpleTreeNode(child, new ArrayList<TreeNode<Object>>());

			parentNode.add(childNode);

			if (!isLeaf) {
				buildTree(childNode, child.id);
			}
		}
	}

	/**
	 * 检查产品是否有子节点
	 */
	private boolean hasChildren(int productId) {
		for (ProductData pd : productMap.values()) {
			if (pd.parentId != null && pd.parentId == productId) {
				return true;
			}
		}
		return false;
	}

	/**
	 * 展开或折叠树
	 */
	private void expandOrCollapse() {
		if (treeExpand.isChecked()) {
			if (m_tree.getTreechildren() != null)
				TreeUtils.expandAll(m_tree);
		} else {
			if (m_tree.getTreechildren() != null)
				TreeUtils.collapseAll(m_tree);
		}
	}

	/**
	 * 设置选中节点并更新详情面板
	 */
	private void setSelectedNode(SimpleTreeNode nd) {
		m_selectedNode = nd;
		if (m_selectedNode == null) {
			btnAddChild.setDisabled(true);
			btnDelete.setDisabled(true);
			return;
		}

		ProductData pd = m_selectedNode.getProductData();

		// 关键修复: 启用操作按钮
		btnAddChild.setDisabled(false);
		// 根节点不能删除
		btnDelete.setDisabled(pd.parentId == null);

		// 清空并重建detailGrid
		detailGrid.getChildren().clear();

		if (!pd.isVirtual) {
			showReadOnlyNodeInfo(pd);
		} else {
			showEditableNodeForm(pd);
		}
	}

	private void showReadOnlyNodeInfo(ProductData pd) {
		detailGrid.getChildren().clear();
		Rows rows = detailGrid.newRows();

		Row row1 = rows.newRow();
		row1.appendChild(new Label("物料编码:"));
		row1.appendChild(new Label(pd.name));

		Row row2 = rows.newRow();
		row2.appendChild(new Label("单位:"));
		row2.appendChild(new Label(pd.unit));

		Row row3 = rows.newRow();
		row3.appendChild(new Label("工序类型:"));
		row3.appendChild(new Label(pd.componentType != null ? pd.componentType : "无"));

		// 隐藏编辑控件
		rgProductType.setVisible(false);
		fieldProduct.getComponent().setVisible(false);
		lblAutoGeneratedName.setVisible(false);
	}

	private void showEditableNodeForm(ProductData pd) {
		System.out.println("=== showEditableNodeForm 被调用 ===");
		System.out.println("节点ID: " + pd.id + ", isLinkExisting: " + pd.isLinkExisting + ", linkedProductId: "
				+ pd.linkedProductId);

		// 先移除旧的监听器
		radioLinkExisting.removeEventListener(Events.ON_CHECK, this);
		radioCreateNew.removeEventListener(Events.ON_CHECK, this);

		// 关键修复: 确保单选按钮组可见
		rgProductType.setVisible(true);
		fieldProduct.getComponent().setVisible(true);
		lblAutoGeneratedName.setVisible(true);

		// 重建表单结构
		Rows rows = detailGrid.newRows();

		// 第一行: 单选按钮组
		Row rowRadio = rows.newRow();
		Hlayout radioLayout = new Hlayout();
		radioLayout.setSpacing("10px");
		radioLayout.appendChild(rgProductType);

		radioLinkExisting.setLabel("关联已有物料");
		radioLinkExisting.setRadiogroup(rgProductType);
		radioLinkExisting.addEventListener(Events.ON_CHECK, this);
		rgProductType.appendChild(radioLinkExisting);

		radioCreateNew.setLabel("创建新物料");
		radioCreateNew.setRadiogroup(rgProductType);
		radioCreateNew.addEventListener(Events.ON_CHECK, this);
		rgProductType.appendChild(radioCreateNew);

		rowRadio.appendChild(radioLayout);

		// 第二行: 物料选择器或自动生成名称
		Row rowProduct = rows.newRow();

		// 关键修复: 先将两个组件都添加到行中,然后控制可见性
		rowProduct.appendChild(fieldProduct.getComponent());
		rowProduct.appendChild(lblAutoGeneratedName);

		if (pd.isLinkExisting) {
			System.out.println("显示物料选择器,设置值: " + pd.linkedProductId);
			radioLinkExisting.setChecked(true);

			// 使用保存的监听器引用
			fieldProduct.removeValuechangeListener(productValueChangeListener);
			fieldProduct.setValue(pd.linkedProductId);
			fieldProduct.addValueChangeListener(productValueChangeListener);

			fieldProduct.getComponent().setVisible(true);
			lblAutoGeneratedName.setVisible(false);
		} else {
			System.out.println("显示自动生成名称: " + pd.name);
			radioCreateNew.setChecked(true);
			lblAutoGeneratedName.setValue(pd.name); // 使用 name 而不是 autoGeneratedName
			lblAutoGeneratedName.setVisible(true);
			rowProduct.appendChild(lblAutoGeneratedName);
			fieldProduct.getComponent().setVisible(false);
		}

		// 重新添加监听器
		radioLinkExisting.addEventListener(Events.ON_CHECK, this);
		radioCreateNew.addEventListener(Events.ON_CHECK, this);

		System.out.println("=== showEditableNodeForm 完成 ===");
	}

	/**
	 * 添加子节点
	 */
	private void action_addChild() {
		if (m_selectedNode == null) {
			Dialog.warn(0, "请先选择一个节点");
			return;
		}

		ProductData parentData = m_selectedNode.getProductData();

		// 创建虚拟节点
		ProductData newProduct = new ProductData(nextTempId--, "", "", "单位", parentData.id, 0);
		newProduct.isVirtual = true; // 标记为虚拟节点
		newProduct.isLinkExisting = false; // 默认创建新物料
		newProduct.name = generateSemiProductName(newProduct); // 生成命名: 根节点编码_层数_序号_流水码

		productMap.put(newProduct.id, newProduct);

		try {
			rebuildTreeFromMemory();
		} catch (Exception e) {
			log.log(Level.SEVERE, "刷新树失败", e);
		}

		Dialog.info(0, "已添加新节点,请编辑详情并保存");
	}

	/**
	 * 删除节点
	 */
	private void action_deleteNode() {
		if (m_selectedNode == null) {
			Dialog.warn(0, "请先选择一个节点");
			return;
		}

		ProductData productData = m_selectedNode.getProductData();

		// 不能删除根节点
		if (productData.parentId == null) {
			Dialog.warn(0, "不能删除根节点");
			return;
		}

		// 检查是否有子节点
		if (hasChildren(productData.id)) {
			Dialog.warn(0, "该节点有子节点,请先删除子节点");
			return;
		}

		// 确认删除
		Dialog.ask(0, "确认删除", "确定要删除节点 '" + productData.name + "' 吗?", new Callback<Boolean>() {
			@Override
			public void onCallback(Boolean result) {
				if (result) {
					performDelete(productData);
				}
			}
		});
	}

	/**
	 * 执行删除操作
	 */
	private void performDelete(ProductData productData) {
		// 虚拟节点直接从内存移除
		if (productData.isVirtual) {
			productMap.remove(productData.id);
		} else {
			// 真实节点标记为删除(但当前版本不支持删除真实节点)
			Dialog.warn(0, "不能删除真实BOM节点");
			return;
		}

		// 从树中移除节点
		SimpleTreeNode parent = (SimpleTreeNode) m_selectedNode.getParent();
		if (parent != null) {
			parent.remove(m_selectedNode);
		}

		// 刷新树
		try {
			rebuildTreeFromMemory();
		} catch (Exception e) {
			log.log(Level.SEVERE, "刷新树失败", e);
		}

		Dialog.info(0, "节点已删除,请保存以确认更改");
	}

	/**
	 * 保存当前节点的修改
	 */
	private void action_saveNodeChanges() {
		if (m_selectedNode == null) {
			return;
		}

		ProductData productData = m_selectedNode.getProductData();

		// 只有虚拟节点才能编辑
		if (!productData.isVirtual) {
			return;
		}

		// 刷新树显示
		try {
			rebuildTreeFromMemory();
		} catch (Exception e) {
			log.log(Level.SEVERE, "刷新树失败", e);
		}

		Dialog.info(0, "修改已暂存,请点击保存按钮确认所有更改");
	}

	/**
	 * 保存所有变更到数据库
	 */
	private void action_saveAll() {
		performSaveAll();
	}

	/**
	 * 执行数据库保存操作 - 将虚拟BOM树保存为独立的BOM版本
	 */
	private void performSaveAll() {
		try {
			// 第一步: 验证所有虚拟节点
			for (ProductData pd : productMap.values()) {
				if (!pd.isVirtual)
					continue;
				if (pd.isLinkExisting && (pd.linkedProductId == null || pd.linkedProductId <= 0)) {
					Dialog.error(0, "虚拟节点 " + pd.name + " 未选择物料");
					return;
				}
			}

			// 获取虚拟BOM树的根节点
			ProductData rootNode = null;
			for (ProductData pd : productMap.values()) {
				if (pd.parentId == null) {
					rootNode = pd;
					break;
				}
			}

			if (rootNode == null) {
				Dialog.error(0, "未找到根节点");
				return;
			}

			// 加载根节点物料信息
			MProduct rootProduct = MProduct.get(Env.getCtx(), rootNode.id);
			if (rootProduct == null) {
				Dialog.error(0, "无法加载根节点物料信息");
				return;
			}

			// 为根节点生成 BOM Value,并从中提取统一版本号
			// 格式: 物料编码_0_V_1_流水号
			String rootSerialCode = String.format("%04d", System.currentTimeMillis() % 10000);
			String rootBOMValue = rootProduct.getValue() + "_0_V_1_" + rootSerialCode;

			// 从 rootBOMValue 中提取流水号部分作为统一版本号
			// 格式: v_1_流水号
			String unifiedRevision = "v_1_" + rootSerialCode;

			System.out.println("根节点BOM Value: " + rootBOMValue);
			System.out.println("统一版本号: " + unifiedRevision);

			Map<Integer, Integer> virtualToRealIdMap = new HashMap<>();

			// 按层级排序处理所有节点(包括根节点)
			List<ProductData> allNodes = new ArrayList<>(productMap.values());
			allNodes.sort((a, b) -> {
				int levelA = calculateNodeLevel(a);
				int levelB = calculateNodeLevel(b);
				if (levelA != levelB)
					return Integer.compare(levelA, levelB);
				return Integer.compare(a.sortOrder, b.sortOrder);
			});

			// 第二步: 处理所有虚拟节点,创建物料
			for (ProductData pd : allNodes) {
				if (!pd.isVirtual)
					continue;

				int productId;
				if (pd.isLinkExisting) {
					// 选择已有物料
					productId = pd.linkedProductId;
				} else {
					// 创建新物料
					MProduct newProduct = new MProduct(Env.getCtx(), 0, null);
					newProduct.setValue(pd.name);
					newProduct.setName(pd.name);

					// 从根节点复制必填字段
					newProduct.setC_UOM_ID(rootProduct.getC_UOM_ID());
					newProduct.setM_Product_Category_ID(rootProduct.getM_Product_Category_ID());
					newProduct.setC_TaxCategory_ID(rootProduct.getC_TaxCategory_ID());
					newProduct.setProductType(rootProduct.getProductType());
					newProduct.setIsStocked(rootProduct.isStocked());
					newProduct.setIsPurchased(rootProduct.isPurchased());
					newProduct.setIsSold(rootProduct.isSold());
					if (rootProduct.getM_AttributeSet_ID() > 0) {
						newProduct.setM_AttributeSet_ID(rootProduct.getM_AttributeSet_ID());
					}

					// 设置自定义字段
					for (Map.Entry<String, Object> entry : rootNode.productCustomFields.entrySet()) {
						newProduct.set_ValueOfColumn(entry.getKey(), entry.getValue());
					}

					newProduct.saveEx();

					productId = newProduct.get_ID();
					virtualToRealIdMap.put(pd.id, productId);
				}
			}

			// 第三步: 为所有非叶子节点创建 PP_Product_BOM 和 PP_Product_BOMLine
			for (ProductData pd : allNodes) {
				// 检查是否有子节点
				boolean hasChildren = false;
				for (ProductData child : productMap.values()) {
					if (child.parentId != null && child.parentId.equals(pd.id)) {
						hasChildren = true;
						break;
					}
				}

				if (!hasChildren) {
					continue; // 叶子节点,跳过
				}

				// 确定当前节点的物料ID
				int currentProductId;
				if (pd.isVirtual) {
					if (pd.isLinkExisting) {
						currentProductId = pd.linkedProductId;
					} else {
						currentProductId = virtualToRealIdMap.get(pd.id);
					}
				} else {
					currentProductId = pd.id;
				}

				// 生成BOM编码和名称
				int level = calculateNodeLevel(pd);
				String bomSerialCode;
				String bomValue;

				// 如果是根节点,使用预先生成的 rootBOMValue
				if (pd.parentId == null) {
					bomValue = rootBOMValue;
				} else {
					// 其他节点使用随机流水号
					bomSerialCode = String.format("%04d", new Random().nextInt(10000));
					MProduct currentProduct = MProduct.get(Env.getCtx(), currentProductId);
					bomValue = currentProduct.getValue() + "_" + level + "_V_1_" + bomSerialCode;
				}

				MProduct currentProduct = MProduct.get(Env.getCtx(), currentProductId);
				String bomName = currentProduct.getName() + " BOM";

				// 确定BOMType
				String bomType;
				if (pd.isVirtual && !pd.isLinkExisting) {
					bomType = MPPProductBOM.BOMTYPE_CurrentActive; // 'A'
				} else {
					bomType = MPPProductBOM.BOMTYPE_ProductConfigure; // 'C'
				}

				// 创建 PP_Product_BOM
				MPPProductBOM bom = new MPPProductBOM(Env.getCtx(), 0, null);
				bom.setM_Product_ID(currentProductId);
				bom.setValue(bomValue);
				bom.setName(bomName);
				bom.setRevision(unifiedRevision); // 使用统一版本号(v_1_流水号格式)
				bom.setBOMType(bomType);
				bom.setBOMUse(MPPProductBOM.BOMUSE_Master);

				// 设置自定义字段
				ProductData parentData = productMap.get(pd.parentId);
				if (parentData != null && parentData.bomCustomFields != null) {
					for (Map.Entry<String, Object> entry : parentData.bomCustomFields.entrySet()) {
						bom.set_ValueOfColumn(entry.getKey(), entry.getValue());
					}
				}

				bom.saveEx();

				// 为该节点的所有子节点创建 PP_Product_BOMLine
				int lineNo = 10;
				for (ProductData child : productMap.values()) {
					if (child.parentId == null || !child.parentId.equals(pd.id)) {
						continue;
					}

					// 确定子节点的物料ID
					int childProductId;
					if (child.isVirtual) {
						if (child.isLinkExisting) {
							childProductId = child.linkedProductId;
						} else {
							childProductId = virtualToRealIdMap.get(child.id);
						}
					} else {
						childProductId = child.id;
					}

					// 创建 PP_Product_BOMLine
					MPPProductBOMLine bomLine = new MPPProductBOMLine(bom);
					bomLine.setM_Product_ID(childProductId);
					bomLine.setLine(lineNo);
					bomLine.setQtyBOM(BigDecimal.ONE);
					bomLine.setQtyBatch(Env.ZERO);
					bomLine.setC_UOM_ID(rootProduct.getC_UOM_ID());
					bomLine.setComponentType(child.componentType != null ? child.componentType : "CO");
					bomLine.setIssueMethod("1");
					bomLine.saveEx();

					lineNo += 10;
				}
			}

			Dialog.info(0, "独立BOM树版本已成功保存到数据库!");
			loadBOMFromDatabase();

		} catch (Exception e) {
			log.log(Level.SEVERE, "保存失败", e);
			Dialog.error(0, "保存失败: " + e.getMessage());
		}
	}

	/**
	 * 关闭表单
	 */
	public void dispose() {
		SessionManager.getAppDesktop().closeActiveWindow();
	}

	@Override
	public void onEvent(Event event) throws Exception {
		// 刷新按钮
		if (event.getTarget().getId().equals(ConfirmPanel.A_REFRESH)) {
			action_loadBOM();
		}
		// 取消按钮
		else if (event.getTarget().getId().equals(ConfirmPanel.A_CANCEL)) {
			dispose();
		}
		// 树展开复选框
		else if (event.getTarget().equals(treeExpand)) {
			expandOrCollapse();
		}
		// 树选择事件
		else if (event.getTarget() instanceof Tree) {
			Treeitem ti = m_tree.getSelectedItem();
			if (ti == null) {
				log.log(Level.WARNING, "GenerateTreeBOM.onEvent treeItem=null");
			} else {
				SimpleTreeNode tn = (SimpleTreeNode) ti.getValue();
				setSelectedNode(tn);
			}
		}
		// 添加子节点按钮
		else if (event.getTarget().equals(btnAddChild)) {
			action_addChild();
		}
		// 删除节点按钮
		else if (event.getTarget().equals(btnDelete)) {
			action_deleteNode();
		}
		// 单选按钮事件
		else if (event.getTarget().equals(radioLinkExisting) || event.getTarget().equals(radioCreateNew)) {
			if (Events.ON_CHECK.equals(event.getName())) {
				onProductTypeChange();
			}
		}
		// 物料选择器事件
		else if (fieldProduct != null && event.getTarget().equals(fieldProduct.getComponent())) {
			System.out.println("=== 通过onEvent监听到物料选择器事件 ===");
			onProductSelected();
		}
		// 保存按钮
		else if (event.getTarget().equals(btnSave)) {
			action_saveAll();
		}
		// 详情字段变更
		else if (event.getTarget().equals(txtName) || event.getTarget().equals(txtType)
				|| event.getTarget().equals(txtDescription) || event.getTarget().equals(txtUnit)
				|| event.getTarget().equals(txtSortOrder)) {
			if (Events.ON_CHANGE.equals(event.getName())) {
				action_saveNodeChanges();
			}
		}
	}

	private void onProductSelected() {
		System.out.println("=== onProductSelected 被调用 ===");
		Integer productId = (Integer) fieldProduct.getValue();
		System.out.println("选择的物料ID: " + productId);

		if (productId == null || productId == 0 || m_selectedNode == null) {
			System.out.println("退出: productId=" + productId + ", m_selectedNode=" + (m_selectedNode != null));
			return;
		}

		ProductData pd = m_selectedNode.getProductData();
		System.out.println("当前节点ID: " + pd.id + ", 原linkedProductId: " + pd.linkedProductId);

		pd.linkedProductId = productId;
		pd.isLinkExisting = true;
		System.out.println("更新后linkedProductId: " + pd.linkedProductId);

		MProduct product = MProduct.get(Env.getCtx(), productId);
		if (product != null) {
			String rootValue = getRootProductValue();
			int level = calculateNodeLevel(pd);
			int sequence = calculateSequenceInLevel(pd);
			String serialCode = String.format("%04d", Math.abs(pd.id));

			pd.name = String.format("%s_%d_%d_%s_%s", rootValue, level, sequence, product.getValue(), serialCode);
			System.out.println("生成的新名称: " + pd.name);

			int selectedNodeId = pd.id;

			try {
				System.out.println("开始刷新树...");
				rebuildTreeFromMemory();
				System.out.println("树刷新完成,开始重新选中节点...");

				Object rawModel = m_tree.getModel();
				if (!(rawModel instanceof SimpleTreeModel)) {
					log.severe("树模型类型不匹配");
				}
				SimpleTreeModel model = (SimpleTreeModel) rawModel;
				DefaultTreeNode<Object> foundNode = findNodeById(model.getRoot(), selectedNodeId);
				if (foundNode != null) {
					System.out.println("找到节点,重新选中...");
					int[] path = model.getPath(foundNode);
					Treeitem ti = m_tree.renderItemByPath(path);
					m_tree.selectItem(ti);
					setSelectedNode((SimpleTreeNode) foundNode);
					System.out.println("节点重新选中完成");
				} else {
					System.out.println("未找到节点!");
				}
			} catch (Exception e) {
				log.log(Level.SEVERE, "刷新树失败", e);
				e.printStackTrace();
			}
		}
	}

	/**
	 * 根据ID查找节点
	 */
	private DefaultTreeNode<Object> findNodeById(TreeNode<Object> root, int targetId) {
		if (root instanceof SimpleTreeNode) {
			SimpleTreeNode node = (SimpleTreeNode) root;
			if (node.getProductData().id == targetId) {
				return node;
			}
		}

		for (int i = 0; i < root.getChildCount(); i++) {
			DefaultTreeNode<Object> found = findNodeById(root.getChildAt(i), targetId);
			if (found != null) {
				return found;
			}
		}

		return null;
	}

	@Override
	public ADForm getForm() {
		return m_frame;
	}

}