#Adempiere
#Mon May 18 17:27:03 CST 2026
CDate=xyz2025-12-26 14\:02\:23.909
WarningD=Einstellungen_nicht_aendern,_da_diese_undokumentierte_Nebenwirkungen_haben.
Warning=Do_not_change_any_of_the_data_as_they_will_have_undocumented_side_effects.
UITheme=xyzAdempiere Theme
StorePassword=xyzN
AutoCommit=xyzY
ShowAcct=xyzY
org.eclipse.jetty.ee8.osgi.annotations.AnnotationParser.TraceLevel=SEVERE
Language=xyzzh_CN
TraceFile=xyzN
CacheWindow=xyzY
PrintPreview=xyzN
ValidateConnectionOnStartup=xyzN
UILookFeel=xyzAdempiere
ShowTrl=xyzN
TempDir=xyzC\:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\
AutoNew=xyzN
ApplicationUserID=xyzGardenAdmin
LoadTabMetaDataBackground=xyzN
SingleInstancePerWindow=xyzN
Connection=xyzCConnection[name\=0.0.0.0{192.168.1.118-idempiere-adempiere},AppsHost\=0.0.0.0,WebPort\=8080,SSLPort\=8443,type\=PostgreSQL,DBhost\=192.168.1.118,DBport\=5432,DBname\=idempiere,BQ\=false,FW\=false,FWhost\=,FWport\=0,UID\=adempiere,PWD\=adempiere]
Charset=xyzUTF-8
DataSource=xyzjava\:adempiereDB
OpenWindowMaximized=xyzN
AutoLogin=xyzN
org.eclipse.jetty.ee8.annotations.AnnotationParser.TraceLevel=SEVERE
AdempiereSys=xyzN
TraceLevel=xyzWARNING
LogMigrationScript=xyzN
